export const root_dir = "/path/to/directory"
export const remoteURL = "https://somecoolurl.com"
export const username = "whoami"
export const password = "supasecretpassword"
export const title = "Some Cool Title"