services:
    app:
        container_name: webdav-index
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - REMOTE_URL=${REMOTE_URL}
            - REMOTE_USERNAME=${REMOTE_USERNAME}
            - REMOTE_PASSWORD=${REMOTE_PASSWORD}
            - REMOTE_ROOT_DIR=${REMOTE_ROOT_DIR}

            - FUZZY_SEARCH=${FUZZY_SEARCH}
            - CACHE_REFRESH=${CACHE_REFRESH}

            - NEXT_PUBLIC_TITLE=${NEXT_PUBLIC_TITLE}
            - NEXT_PUBLIC_DESCRIPTION=${NEXT_PUBLIC_DESCRIPTION}
        ports:
            - ${DOCKER_PORT}:3000
        restart: unless-stopped
